name: Build SAMLAuthenticator Image

on:
  pull_request:
    branches: [ master ]
    paths:
      # All files critical to the SAMLAuthenticator image
      - 'jupyterhub-samlauthenticator/Dockerfile'
      # And this file, for good measure
      - '.github/workflows/authenticator-build.yml'
  schedule:
    # Run at 00:00 UTC on the first day of every month
    - cron: '0 0 1 * *'
    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the JupyterHub-SAMLAuthenticator image
      run: docker build jupyterhub-samlauthenticator
